[package]
name = "home"
version = "0.1.1"
authors = ["Alsan Ali <morrutplz@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serenity = "0.10"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
toml = "0.5"